CREATE TABLE short_urls
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url        TEXT NOT NULL ,
    short_code VARCHAR(255) UNIQUE ,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_short_urls PRIMARY KEY (id)
);